### ISSUE TITLE
Not working on latest everything.

### ISSUE THREAD

**Issue by borgauf** [harsman/dyalog-mode#5]
I've got Dyalog APL/S-64 Version 18.2.45405 installed on Ubuntu 22.10 and Emacs 28.2 with dyalog-mode latest from elpa. I open a *.dyalog file in Emacs and it seems to be recognized as a dyalog file, but there is no menu for dyalog. How am I supposed to start a REPL? I guess with M-x dyalog-ride-session, but after asking me for Host (I chose default localhost) and Port (I chose default 8080) it gives me back

failed: Connection refused, :name, dyalog-ride, :buffer,  *dyalog-ride-receive*-790033, :host, localhost, :service, 8080, :sentinel, dyalog-editor-sentinel, :filter, dyalog-ride-receive, :coding, no-conversion

Then I start dyalog at the command line terminal REPL and try

]load ~/.emacs.d/elpa/dyalog-mode-20221205.814/Emacs.apl     
#.Emacs
Emacs.editor.setupmenu ⍬
VALUE ERROR                                                                                                                     │
setupmenu[2] '⎕SE.popup.emacs'⎕WC'MenuItem'('Caption'('Edit in Emacs',⎕AV[10],title)) 
                                                     ∧

No idea how to proceed.

**Comment by harsman** [comment]
The setupmenu stuff only works on Windows. On Linux you can use RIDE to talk to a Dyalog process, but you need to tell Dyalog to listen for RIDE connections.

RIDE_INIT="serve:*:8989" mapl

Should launch a dyalog process which you can connect to from Emacs by doing M-x dyalog-ride-session and selecting localhost and port 8989.

There is no facility in dyalog-mode to launch Dyalog from Emacs.
